#!/bin/bash
#./files/rebuild

# Build and compile the visualizer library
cd _BUILD
rm CMakeCache.txt cmake_install.cmake Makefile
rm -r CMakeFiles lib hans_visual
cmake -G"Unix Makefiles" ..
make

# Build and compile the example project
cd ../example/_BUILD
rm CMakeCache.txt cmake_install.cmake Makefile Shaper imgui.ini
rm -r CMakeFiles
cmake -G"Unix Makefiles" ..
make
./Shaper
